language: objective-c
osx_image: xcode8
xcode_project: Luhn.xcodeproj
xcode_scheme: Luhn

env:
  - ACTION=test  PLATFORM=Mac
  - ACTION=test  PLATFORM=iOS
  - ACTION=build PLATFORM=watchOS DESTINATION='platform=watchOS Simulator,name=Apple Watch - 38mm'
  - ACTION=test  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'

script:
  - set -o pipefail && xcodebuild -scheme Luhn -destination "$DESTINATION" $ACTION | xcpretty
  - carthage build --no-skip-current