codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...90"
  status:
    patch:
      default:
        threshold: 2

ignore:
  - LuhnTests/*

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false
  branches: null
  flags: null
  paths: null
